### ISSUE TITLE
module api --- defining libwhen using CLFFT on Windows

### ISSUE THREAD

**Issue by sherrinm** [JuliaGPU/CLFFT.jl#1]
When using the package under Windows it does not assign the "libclfft" constant appropriately

I think this was corrected in CLBLAS but not in CLFFT and just needs an @windows_only defn:
i.e.
@unix_only        const libclfft = "libclFFT"
@windows_only const libclfft = "clFFT"

Then examples/test seem to work for me

**Comment by jakebolewski** [comment]
Thanks @sherrinm, could you create a PR?  As you said, should be a simple 1-line fix.

**Comment by sherrinm** [comment]
Sure but not today as in Frankfurt

**Comment by juliohm** [comment]
This issue can be closed I think.

**Comment by dfdx** [comment]
Corresponding PR for reference: #2
