### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CLFFT.jl#24]
I get `LoadError: Provider BinDeps.Binaries failed to satisfy dependency libCLFFT` while trying to build. Full gist below. Is this something I need to install or is it something done automatically?

https://gist.github.com/denizyuret/45f867a2746816ecdf303b169dda7bf7

**Comment by vchuravy** [comment]
You will need to install libcfft and libcfft-dev I think. What kind of
system are you on?

**Comment by denizyuret** [comment]
Hm, it looked like it was trying to do that automatically but maybe I
misunderstood.  I am on Centos7.

**Comment by vchuravy** [comment]
That means most often that it can't load the library that we tried to download.
Can you run `ldd` on the file in `/dev/shm/dyuret/.julia/v0.6/CLFFT/deps/clFFT-2.12.2-Linux-x64` to see if there are any missing dependencies?

**Comment by denizyuret** [comment]
Looks like it is not happy about libOpenCL:
https://gist.githubusercontent.com/denizyuret/c5ff63773345d020ebebd2d0790a4be6/raw/82dd3e196ba10c7a732475afd721be107e36d1e5/clfft-build-error-2
