### ISSUE TITLE
Build fails on latest version, succeeds on git master

### ISSUE THREAD

**Issue by JMurph2015** [JuliaGPU/CLFFT.jl#26]
Hi!
I'm on Arch Linux, and the build fails out on BinDeps with the latest published version, but if I clone from Github, it builds fine.  Could someone do a version bump to push this into METADATA.jl?
Thanks!

**Comment by vchuravy** [comment]
Should be fixed by `v0.5.2` https://github.com/JuliaGPU/CLFFT.jl/releases/tag/v0.5.2
