### ISSUE TITLE
Request to become new maintainer of CLFFT.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/CLFFT.jl#37]
We are working on a research project that is revamping some of the OpenCL packages for the current stable release of the language. We need write access to merge PRs and trigger new releases.

Appreciate if someone in @JuliaGPU can add me to the list of CLFFT.jl' maintainers.

cc: @dfdx @vchuravy @maleadt @ranocha

**Comment by maleadt** [comment]
I've added you to the OpenCL team, which should give you write permissions to most OpenCL packages in JuliaGPU.

**Comment by juliohm** [comment]
Thank you Tim, will accept the invitation as soon as I reach my desktop.

Em qui., 22 de set. de 2022 08:46, Tim Besard ***@***.***>
escreveu:
