### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/CLFFT.jl#4]
Could you please elaborate on the status of this package? Is it ready for use?

I am planning to replace Julia's `fft()` by the OpenCL version in one of my packages to take advantage of Intel and NVIDIA cards. Do you have an estimate of speedup?

**Comment by juliohm** [comment]
I've tested the package and it is working on my Intel on-board graphics card with the Beignet driver. I have a bunch of warnings in the latest stable of the package though. Could you please tag a new version for Julia v0.4?

**Comment by dfdx** [comment]
Created a PR for this: JuliaLang/METADATA.jl#4954

**Comment by juliohm** [comment]
Thank you @dfdx, looking forward to close the issue :+1:

**Comment by juliohm** [comment]
I saw you merged the tag, thank you, closing the issue.
