### ISSUE TITLE
2D/3D FFT example

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/CLFFT.jl#5]
I am trying to write the classical [tiled convolution](http://developer.amd.com/resources/documentation-articles/articles-whitepapers/tiled-convolution-fast-image-filtering/) with OpenCL FFT instead of Julia's `fft()`. Consider the following working version on the CPU adapted from Tim's `Images.jl` package:

https://gist.github.com/juliohm/7241fb1c1431bf29237cad35194ee6c8

Specifically, consider [this line](https://gist.github.com/juliohm/7241fb1c1431bf29237cad35194ee6c8#file-imfilter_gpu-jl-L15) where the forward and inverse FFT are being applied to multidimensional arrays. Could someone with more experience in OpenCL help me plan this FFT and perform this task? How would you pass a `Plan` object to the `imfilter_gpu()` function and use it over multiple calls?

I deeply appreciate if you can provide some starting code, I am coming from the NVIDIA world (got tired of portability issues).

**Comment by SimonDanisch** [comment]
You might want to try [ArrayFire.jl](https://github.com/JuliaComputing/ArrayFire.jl), which should make this easier!
I'm not sure about the `Plan`. Seems like it depends on the size, so it can't be reused that easily.
So maybe just create a new plan for every call, and if that seems expensive cache them with a Dict?

But to be honest, I don't exactly know what I'm talking about, since this is my first look at CLFFT.
I guess you should look at http://clmathlibraries.github.io/clFFT/ ;)

**Comment by juliohm** [comment]
Hi Simon,

Thanks for the suggestion, I knew about the C++ ArrayFire library, good to know that there is a Julia wrapper nowadays. ArrayFire uses the OpenCL FFT [behind the scenes](http://arrayfire.com/clmath-an-open-source-blas-and-fft-library-for-opencl/) and therefore has some extra overhead compared to the more simple wrapper `CLFFT.jl`. I am reading the docs of clFFT on GitHub, it takes some time to get used to all this low level machinery. I was wondering if someone else had performed that task before to save me some time :blush:

**Comment by SimonDanisch** [comment]
Sorry ;) That wouldn't be me. If you're looking forward to visualize the 3D result directly from GPU memory, I'd be quite curious to add that to GLVisualize as an example, though!

**Comment by juliohm** [comment]
Sounds great! I am also very interested in visualizing 3D arrays without dumping them to an external file and having to open a dedicated visualization program. Do you know any way that I could visualize 3D arrays directly on Jupyter notebooks? Something like a OpenGL interactive visualization window with basic features such as rotation and zoom.

**Comment by SimonDanisch** [comment]
I actually just recently prototyped Jupyter integration, but it's still static since it's quite a bit involved to catch the mouse events for the notebook window (at least for someone with no clue about web stuff)... But GLVisualize does work with Jupyter and an external window. One could think about creating an external interactive window and dumping a screenshot of that into the notebook.

**Comment by juliohm** [comment]
That is exciting, I will give it a check. Thank you for sharing!

**Comment by MichaelQuell** [comment]
I think this could do
[https://gist.github.com/MichaelQuell/8d9e692a8fb7f67cc6a6ab0200f70f81](https://gist.github.com/MichaelQuell/8d9e692a8fb7f67cc6a6ab0200f70f81)

if this is any help.

**Comment by bragadeesh** [comment]
Hello,
Did you have a chance to look at example code in clFFT here:
https://github.com/clMathLibraries/clFFT/tree/master/src/examples

It has examples for 1/2/3d complex FFTs. The real FFTs are similar but a little more steps are needed to explicitly set strides and distances correctly. The real FFT section in clFFT documentation explains this:
http://clmathlibraries.github.io/clFFT/index.html#RealFFT

**Comment by juliohm** [comment]
Thank you for your help @MichaelQuell ! I really appreciate it. I am debugging the code on my graphics card and adapting it to my use case. I will close this issue soon I get everything working. You saved me a lot of  headache.

**Comment by juliohm** [comment]
@bragadeesh thank you for all the links, they are also very helpful. I think @MichaelQuell has completely solved the issue and I can move on with my research.

**Comment by MichaelQuell** [comment]
@juliohm i updated the file a minute ago because the multiplication was only for real numbers

**Comment by juliohm** [comment]
@MichaelQuell I actually only need it for real numbers :+1:

**Comment by juliohm** [comment]
@MichaelQuell, I updated the gist to operate on `Float32` but for some reason I am getting a segfault. Do you have an idea of what may be the cause of the issue?

https://gist.github.com/juliohm/7241fb1c1431bf29237cad35194ee6c8

Can you reproduce the segfault in your hardware? `julia imfilter_gpu.jl`

It seems that the segmentation fault is happening after the GPU has finished its work and the memory has been copied back. I get a bunch of messages regarding Julia's garbage collector:

> signal (11): Segmentation fault
> pthread_mutex_lock at /usr/lib/libpthread.so.0 (unknown line)
> unknown function (ip: 0x7f6b2739e773)
> get_last_event at /usr/lib/beignet//libcl.so (unknown line)
> cl_event_delete at /usr/lib/beignet//libcl.so (unknown line)
> clReleaseEvent at /usr/lib/beignet//libcl.so (unknown line)
> clReleaseEvent at /usr/lib/libOpenCL.so.1 (unknown line)
> _finalize at /home/juliohm/.julia/v0.4/OpenCL/src/macros.jl:4
> jl_apply_generic at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> anonymous at /home/juliohm/.julia/v0.4/OpenCL/src/event.jl:31
> unknown function (ip: 0x7f6d3eeaa05f)
> jl_gc_collect at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> unknown function (ip: 0x7f6d3eeb1c77)
> jl_gc_allocobj at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> jl_alloc_array_3d at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> call at essentials.jl:202
> anonymous at /home/juliohm/Desktop/imfilter_gpu.jl:100
> unknown function (ip: 0x7f6d3eea46c3)
> unknown function (ip: 0x7f6d3eea52dc)
> jl_load at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> include at ./boot.jl:261
> jl_apply_generic at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> include_from_node1 at ./loading.jl:320
> jl_apply_generic at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> process_options at ./client.jl:284
> _start at ./client.jl:378
> unknown function (ip: 0x7f6d3c0e6889)
> jl_apply_generic at /home/juliohm/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
> unknown function (ip: 0x401aa7)
> unknown function (ip: 0x4016af)
> __libc_start_main at /usr/lib/libc.so.6 (unknown line)
> unknown function (ip: 0x4016f9)
> unknown function (ip: (nil))
> Segmentation fault (core dumped)

**Comment by juliohm** [comment]
`CLFFT.jl` tests aren't passing in my laptop as reported in #7.

**Comment by MichaelQuell** [comment]
The problem is, at the moment i dont know how to get the the real_to_complex fft to work. 
Also the fft has **always complex** numbers as output, so you would need the updated multiplication function

**Comment by juliohm** [comment]
Makes sense, maybe this code can work regardless of the other driver issues? I am installing an OS from scratch in my old laptop with a GPU card to make sure everything is clean and properly configured.

**Comment by juliohm** [comment]
@MichaelQuell I finally had time to look into this issue again, the implementation is working with the tests I have run: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/imfilter_gpu.jl

I am getting 2.5x speed up on my integrated Intel(R) Skylake graphics card, will test on another laptop  with a dedicated NVIDIA GeForce. Please let me know if you see any place where the performance can be improved.
